name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |

            cd ~/practice

            git pull

            sudo docker stop portfolio || true

            sudo docker rm portfolio || true

            sudo docker build -t practice-docker .

            sudo docker run -d \
              --name practice-container \
              -p 8080:80 \
              practice-docker

            sudo systemctl reload nginx